---

- name: Wait for connection
  wait_for_connection:
    delay: 30
    timeout: 300

- name: Gathering facts
  ansible.builtin.setup:

- name: Pause for 60 seconds to wait for server to become responsible
  wait_for:
    timeout: 60
